---
collections:
- name: ansible.posix
  version: ">=1.5.1" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: fedora.linux_system_roles
  version: ">=1.21.0" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: community.general
  version: ">=6.4.0" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: infra.controller_configuration
  version: "2.5.2" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: infra.leapp
  version: "1.1.3" # Version range identifiers (default: ``*``)
  source: https://galaxy.ansible.com # The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)
- name: https://github.com/heatmiser/ansible-snapshot.git
  type: git
  version: main
- name: https://github.com/swapdisk/lvm_snapshots.git
  type: git
  version: main
- name: https://github.com/ygalblum/ansible-bash-shrink-lv#infra.lvm_tools/shrink_lv
  type: git
  version: prelight-checks
...
