---
controller_templates:
  - name: OS / Patch OS to latest
    project: Project Leapp
    playbook: pkgs_full_update.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
  - name: AUTO / 01 Analysis
    project: Project Leapp
    playbook: analysis.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    extra_vars:
      leapp_upgrade_type: rhui
      leapp_repos_enabled: []
    ask_variables_on_launch: true
  - name: AUTO / 01 Analysis / RHEL6
    project: Project Leapp
    playbook: analysis.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel6
          required: true
    extra_vars:
      leapp_upgrade_type: rhui
      leapp_repos_enabled: []
      analysis_repos_el6:
        - rhui-REGION-rhel-server-extras
        - rhui-REGION-rhel-server-releases-optional
    ask_variables_on_launch: true
    ask_limit_on_launch: true
    execution_environment: Ansible Engine 2.9 execution environment
  - name: OS / Upgrade
    project: Project Leapp
    playbook: upgrade.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    extra_vars:
      leapp_upgrade_type: rhui
      leapp_repos_enabled: []
    ask_variables_on_launch: true
  - name: OS / Upgrade / RHEL6
    project: Project Leapp
    playbook: upgrade.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel6
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    extra_vars:
      leapp_upgrade_type: rhui
      leapp_repos_enabled: []
    ask_variables_on_launch: true
    execution_environment: Ansible Engine 2.9 execution environment
  - name: OS / Remediation
    project: Project Leapp
    playbook: remediate.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
  - name: PETS / App Install
    project: Project Leapp
    playbook: pet_clinic.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
  - name: UTILITY / Snapshot Instance
    project: Project Leapp
    playbook: snapshot_instance.yml
    inventory: Workshop Inventory
    limit: ansible-1
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    extra_vars:
      snapshot: aws
      ec2_stop_instance_for_snapshot: false
      ec2_region: "{{ workshop_ec2_region }}"
      instances_template:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
  - name: UTILITY / Snapshot Delete
    project: Project Leapp
    playbook: snapshot_delete.yml
    inventory: Workshop Inventory
    limit: ansible-1
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    extra_vars:
      snapshot: aws
      ec2_region: "{{ workshop_ec2_region }}"
      instances_template:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
  - name: AUTO / 03 Rollback
    project: Project Leapp
    playbook: rollback.yml
    inventory: Workshop Inventory
    limit: ansible-1
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    extra_vars:
      snapshot: aws
      delete_prior_volume: true
      ec2_region: "{{ workshop_ec2_region }}"
      instances_template:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
  - name: UTILITY / Instance Details
    project: Project Leapp
    playbook: instance_details.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    extra_vars:
      ec2_region: "{{ workshop_ec2_region }}"
      instances:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
  - name: UTILITY / Snapshot Details
    project: Project Leapp
    playbook: snapshot_details.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    extra_vars:
      snapshot: aws
      ec2_region: "{{ workshop_ec2_region }}"
      snapshots:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          Environment: leapp
  - name: UTILITY / Update inventories via dynamic sources
    project: Project Leapp
    playbook: inventory_source_update.yml
    inventory: Workshop Inventory
    credentials:
      - Controller Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory to update
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel6
            - rhel7
            - rhel8
            - rhel9
          required: true
  - name: UTILITY / Fact Scan
    project: Project Leapp
    playbook: fact_scan.yml
    inventory: Workshop Inventory
    use_fact_cache: true
    credentials:
      - Workshop Credential
    extra_vars:
      _hosts: all
  - name: UTILITY / Set instance tags
    project: Project Leapp
    playbook: set_instance_tags.yml
    inventory: Workshop Inventory
    limit: ansible-1
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: Enter server name - Leave blank to target all
          type: text
          variable: ripu_pet_name
          required: false
    extra_vars:
      ec2_region: "{{ workshop_ec2_region }}"
      instances_template:
        tags:
          guid: "{{ lookup('env', 'AWX_HOST').split('.')[1] }}"
          Student: "{{ lookup('env', 'AWX_HOST').split('.')[0] | urlsplit('hostname') }}"
          operating_system: rhel
...
