---
controller_workflows:
  - name: AUTO / 02 Upgrade
    description: Workflow for Snapshot and Leapp Upgrade
    extra_vars:
      lvm_snapshots_action: create
    inventory: Workshop Inventory
    state: present
    organization: Default
    survey_enabled: true
    survey_spec:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
    ask_limit_on_launch: true
    simplified_workflow_nodes:
      - identifier: UTILITY / Snapshot Instance
        unified_job_template: UTILITY / Snapshot Instance
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - OS / Upgrade
      - identifier: OS / Upgrade
        unified_job_template: OS / Upgrade
        organization: Default
        all_parents_must_converge: false
        success_nodes: []
  - name: AUTO / 04 Commit
    description: Workflow for Snapshot delete and Update instance tags
    extra_vars:
      lvm_snapshots_action: remove
    inventory: Workshop Inventory
    state: present
    organization: Default
    survey_enabled: true
    survey_spec:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
    ask_limit_on_launch: true
    simplified_workflow_nodes:
      - identifier: UTILITY / Snapshot Instance
        unified_job_template: UTILITY / Snapshot Instance
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - UTILITY / Set instance tags
      - identifier: UTILITY / Set instance tags
        unified_job_template: UTILITY / Set instance tags
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - EC2 Dynamic Source - rhel7
      - identifier: EC2 Dynamic Source - rhel7
        unified_job_template: EC2 Dynamic Source - rhel7
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes:
          - EC2 Dynamic Source - rhel8
      - identifier: EC2 Dynamic Source - rhel8
        unified_job_template: EC2 Dynamic Source - rhel8
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes:
          - EC2 Dynamic Source - rhel9
      - identifier: EC2 Dynamic Source - rhel9
        unified_job_template: EC2 Dynamic Source - rhel9
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes: []
  - name: WORKFLOW / 01 Standard Process
    description: Workflow for Complete Leapp Upgrade
    extra_vars:
      lvm_snapshots_action: create
    inventory: Workshop Inventory
    state: present
    organization: Default
    survey_enabled: true
    survey_spec:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory group
          type: multiplechoice
          variable: rhel_inventory_group
          choices:
            - ALL_rhel
            - rhel7
            - rhel8
            - rhel9
          required: true
        - question_name: If using limit, repeat node name here. Otherwise leave blank to target all.
          type: text
          variable: ripu_pet_name
          required: true
    ask_limit_on_launch: true
    simplified_workflow_nodes:
      - identifier: WORKFLOW SUB-TEMPLATE/ 01 Analysis
        unified_job_template: WORKFLOW SUB-TEMPLATE/ 01 Analysis
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - OS / Remediation
      - identifier: OS / Remediation
        unified_job_template: OS / Remediation
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - WORKFLOW SUB-TEMPLATE/ 02 Analysis
      - identifier: WORKFLOW SUB-TEMPLATE/ 02 Analysis
        unified_job_template: WORKFLOW SUB-TEMPLATE/ 02 Analysis
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - AUTO / 02 Upgrade
      - identifier: AUTO / 02 Upgrade
        unified_job_template: AUTO / 02 Upgrade
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - UTILITY / Snapshot Instance
      - identifier: UTILITY / Snapshot Instance
        unified_job_template: UTILITY / Snapshot Instance
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - UTILITY / Set instance tags
      - identifier: UTILITY / Set instance tags
        unified_job_template: UTILITY / Set instance tags
        organization: Default
        all_parents_must_converge: false
        success_nodes:
          - EC2 Dynamic Source - rhel7
      - identifier: EC2 Dynamic Source - rhel7
        unified_job_template: EC2 Dynamic Source - rhel7
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes:
          - EC2 Dynamic Source - rhel8
      - identifier: EC2 Dynamic Source - rhel8
        unified_job_template: EC2 Dynamic Source - rhel8
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes:
          - EC2 Dynamic Source - rhel9
      - identifier: EC2 Dynamic Source - rhel9
        unified_job_template: EC2 Dynamic Source - rhel9
        organization: Default
        all_parents_must_converge: false
        type: inventory_source
        success_nodes: []
...
