---
- name: Analysis
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  pre_tasks:
    - name: Include additional analysis packages from vars file
      ansible.builtin.include_vars:
        file: analysis_packages.yml
        hash_behaviour: merge
  roles:
    - infra.leapp.analysis
  tasks:
    - name: Confirm check_vdo True in leapp answerfile
      ansible.builtin.replace:
        path: /var/log/leapp/answerfile
        regexp: '(\[check_vdo\][^<]*)\#\ confirm\ \='
        replace: '\1confirm\ \=\ True'
...
