---
- name: Analysis
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  strategy: free
  gather_facts: true
  become: true
  force_handlers: true
  roles:
    - role: infra.leapp.analysis
      vars:
        analysis_packages_el7:
          - leapp-rhui-aws
          - leapp-upgrade
          - cockpit
          - cockpit-system
          - cockpit-leapp
        analysis_packages_el8:
          - leapp-rhui-aws
          - leapp-upgrade
          - cockpit
          - cockpit-system
          - cockpit-leapp
          - vdo
  tasks:
    - name: Confirm check_vdo True in leapp answerfile
      ansible.builtin.replace:
        path: /var/log/leapp/answerfile
        regexp: '(\[check_vdo\][^<]*)\#\ confirm\ \='
        replace: '\1confirm\ \=\ True'
...
