---
- name: AAP2 Controller configuration via IaC
  hosts: "{{ HOSTS | default('control[0]') }}"
  connection: local
  vars:
    controller_infra_workloads:
      - infra.controller_configuration.projects
      - infra.controller_configuration.execution_environments
      - infra.controller_configuration.inventories
      - infra.controller_configuration.inventory_sources
      - infra.controller_configuration.job_templates
      - infra.controller_configuration.workflow_job_templates
    controller_hostname: "{{ lookup('env', 'TOWER_HOST') }}"
    controller_validate_certs: false

  tasks:
    - name: Gather EC2 metadata facts
      amazon.aws.ec2_metadata_facts:

    - name: Set vars from EC2 metadata
      ansible.builtin.set_fact:
        workshop_ec2_region: "{{ ansible_ec2_instance_identity_document_region }}"

    - name: Configure controller from project group_vars
      ansible.builtin.include_role:
        name: "{{ controller_infra_vars }}"
      loop: "{{ controller_infra_workloads }}"
      loop_control:
        loop_var: controller_infra_vars
...
