---
- name: Scan host for facts
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  become: true

  tasks:
    - name: Get packages
      ansible.builtin.package_facts:

    - name: Get services
      ansible.builtin.service_facts:
...
