---
- name: Set instance tag
  hosts: "{{ all | default('control[0]') }}"
  connection: local
  gather_facts: false
  vars:
    instances: "{{ instances_template }}"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Primary playbook loop over ansible_play_hosts
      ansible.builtin.include_tasks: set_instance_tags_incl.yml
      loop: "{{ ansible_play_hosts }}"
      loop_control:
        loop_var: ansible_loop_host
...
