---
- name: Delete snapshot of instance
  hosts: "{{ 'control[0]' | default(omit) }}"
  connection: local
  gather_facts: false
  vars:
    ec2_instance_action: "snapshot_delete"
    instances: "{{ instances_template }}"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Set snapshots variables from instances variables
      ansible.builtin.set_fact:
        snapshots:
          tags:
            Student: "{{ instances.tags.Student }}"
            guid: "{{ instances.tags.guid }}"
            Environment: leapp
            operating_system: rhel

    - name: Set instance and snapshot tag os_major_version based on survey
      when: rhel_inventory_group != "ALL_rhel"
      block:
        - name: Set instances_combine os_major_version tag for combination merge
          ansible.builtin.set_fact:
            instances_combine:
              tags:
                os_major_version: "{{ rhel_inventory_group | regex_replace('rhel') }}"

        - name: Combine instance extra_var tags with survey-based instance tag os_major_version
          ansible.builtin.set_fact:
            instances: "{{ instances_template | ansible.builtin.combine(instances_combine, recursive=true) }}"

        - name: Set snapshots_combine os_major_version tag for combination merge
          ansible.builtin.set_fact:
            snapshots_combine:
              tags:
                os_major_version: "{{ rhel_inventory_group | regex_replace('rhel') }}"

        - name: Combine survey-based snapshot tag os_major_version with existing snapshots definition
          ansible.builtin.set_fact:
            snapshots: "{{ snapshots | ansible.builtin.combine(snapshots_combine, recursive=true) }}"  

    - name: Set instance tag short_name based on survey
      when: ripu_pet_name is defined
      block:
        - name: Set instances_combine2 short_name tag for combination merge
          ansible.builtin.set_fact:
            instances_combine2:
              tags:
                short_name: "{{ ripu_pet_name }}"

        - name: Combine instance extra_var tags with survey-based instance tag short_name
          ansible.builtin.set_fact:
            instances: "{{ instances | ansible.builtin.combine(instances_combine2, recursive=true) }}"

        - name: Set snapshots_combine2 Instance_short_name tag for combination merge
          ansible.builtin.set_fact:
            snapshots_combine2:
              tags:
                Instance_short_name: "{{ ripu_pet_name }}"

        - name: Combine snapshots tags with survey-based short_name
          ansible.builtin.set_fact:
            snapshots: "{{ snapshots | ansible.builtin.combine(snapshots_combine2, recursive=true) }}"

    - name: Get snapshot details
      ansible.builtin.include_role:
        name: heatmiser.ansible_snapshot.aws
        tasks_from: snapshot/get_snapshot_details

    - name: Delete snapshot of instance
      ansible.builtin.include_role:
        name: heatmiser.ansible_snapshot.aws
        tasks_from: snapshot/snapshot_delete
...

