---
- name: Upgrade
  hosts: "{{ rhel_inventory_group | default(omit) }}"
  strategy: free
  become: true
  force_handlers: true
  vars:
    async_timeout_maximum: 3600
    async_poll_interval: 30
  #   ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: Perform OS upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
...
